GET http://localhost:4000/scrap/localCodes HTTP/1.1

###
GET http://localhost:4000/scrap/getRTMSDataSvcSHRent HTTP/1.1

###
GET http://localhost:4000/scrap/setLocalCodes HTTP/1.1

###
POST http://localhost:4000/sms/send HTTP/1.1

###
GET http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcLandTrade?serviceKey=P%2B%2Fy%2FR84yS9jBDWOea6o%2BooWcZ1t9SRKQaKK23tR2DeF8HGCMh%2B61cTAFpV71qF7HdooH1nZsvvv8MtVGq71Fw%3D%3D HTTP/1.1